const nodeInformation  = [
    [{title: "blanc.cc", description: "BLANC was a minimalistic mod solo created to create a cheap and high quality experience. Developed with C++, it featured a intuitive custom menu and innovative features.", image: "assets/projectimages/blanc.png", link: "https://www.youtube.com/watch?v=KFTPawJKcR4"}],
    [{title: "Shorts Generator", description: "This tool was developed based on the public ShortGPT framework. This project implemented free versions of GPT, Voice2Text and included higher quality voice production. This system was developed as an improvement over the publicly available source, as it required API access keys. This did not, and featured more detailed prompts and captioning systems. Used to post to automatic youtube shorts to multiple channels and funnel viewers to alternative forms of revenue.", image: "assets/projectimages/shortGPT.png", link: "#"},
      {title: "RedEyeCheats V5", description: "RedEyeCheatsV5 was a C++ commision project developed for a provider as they had lost their developer. Working with the provider and against time constraints, RedEyeCheatsV5 was solo developed to meet the demands and security needs of a client.", image: "assets/projectimages/redeye.png", link: "https://www.youtube.com/watch?v=OEfR0n84zX8"}, 
       {title: "EdgeAim V1", description: "EdgeAim V1 was developed as a client request for my late friend Swift. This project was designed around the Window 10 settings GUI, and aimed to replicate it. This project was still in development when he passed, stopping the development. Rest in peace Swift.", image: "assets/projectimages/edgeaim_v1.png", link: "#"}],
    [{title: "Radical Heights", description: "During the battle royal phase, a 70s themed Radical Heights game was released. This client was developed before the game was shut down a few months later, based upon unreal engine. Featured a new design of GUI.", image: "assets/projectimages/radialheights.png", link: "#"},
       {title: "EdgeAim AI Aimbot", description: "Utilising YOLOv5, this universal aimbot was trained on a custom gathered dataset spanning 6 different games. Training images were collected using custom clients. This was linked to an online GUI for easy modification of settings, and featured innovative features such as AI weapon detection for weapon specific settings. This was developed using C++ and HTML, javascript, php, and related open source projects, intended for selling but was never saw a public released. ", image: "assets/projectimages/edgeaim.png", link: "#"}, 
       {title: "Rules Of Survival", description: "This client was developed for the game Rules of Survival before its rework. This included game-breaking features such as teleportation, height adjustment and many other features. Due to the limited restrictions on writing memory within this game, many features were possible that SHOULD NOT have been possible on an online game. Videos of this client achieved 200k views on YouTube.", image: "assets/projectimages/rulesofsurvival.png", link: "#"}],
    [{title: "Edge MM Loader", description: "With a design inspired by GeForce experience, this was a manual map injector designed for the EdgeAim V1 website, intended for multiple different games.", image: "assets/projectimages/manualmap.png", link: "#"}, 
      {title: "CSFloat Price-gap ", description: "I developed this tool to find listings on CSFloat (A CS2 marketplace) with a high margin between its counterpart listed on the steam market. By buying these items and re-selling on the steam market, you can achieve a profit. This is due to steam market prices being inflated. This steam balance can then be exchanged for Steam decks, which can then be sold for cash, starting the cycle again. This tool will automatically find prices with the perfect margins. Written in python.", image: "assets/projectimages/csfloat.png", link: "#"}, 
      {title: "reVival", description: "reVival was a 2D survival game developed from pure C++ without a game engine. This was created for an Alevel games project to challenge myself in new areas at the time. This game featured a full entity system, breakable entities, drops, GL Based rendering and context of position layering.", image: "assets/projectimages/reVival.png", link: "#"}],
    [{title: "drawAuth", description: "drawAuth uses the power of machine learning to recognise imposters attempting to access your phone through grid-unlock by learning how your finger moves. This was developed as part of my dissertation, collecting data from 15 participants and achieved an impressive EER of 0.17 percent. This was written in javascript with flask for the web-app, and Python for the data analysis.", image: "assets/projectimages/drawauth.png", link: "#"}]
  ]